In [6]:
import lancedb
from dotenv import load_dotenv

load_dotenv()

db = lancedb.connect(uri = "../knowledge_base")
db

LanceDBConnection(uri='/Users/aigineer/Documents/github/RAG_mlops25/rag/src/rag/explorations/../knowledge_base')

In [7]:
db["articles"]

LanceTable(name='articles', version=12, _conn=LanceDBConnection(uri='/Users/aigineer/Documents/github/RAG_mlops25/rag/src/rag/explorations/../knowledge_base'))

In [8]:
db["articles"].to_pandas()

,document_name,filepath,content,embedding
0,tiger.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050..."
1,panda.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07891846, 0.018447876, -0.00818634, -0.0604..."
2,kanin.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021530151, -0.024368286, 0.004486084, -0.0..."
3,krabba.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011001587, -0.032714844, -0.049072266, -0.0..."
4,fisk.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.05697632, 0.020736694, -0.028640747, -0.049..."

In [9]:
db["articles"].search("vad äter pandor?").to_pandas()

,document_name,filepath,content,embedding,_distance
0,panda.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,"Jättepanda (Ailuropoda melanoleuca), panda, pa...","[0.07891846, 0.018447876, -0.00818634, -0.0604...",0.805973
1,krabba.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Krabbor (Brachyura) är en delordning av vatten...,"[0.011001587, -0.032714844, -0.049072266, -0.0...",0.968146
2,tiger.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Tiger (Panthera tigris) är ett kattdjur som en...,"[0.022979736, 0.03173828, -0.004386902, -0.050...",0.989740
3,fisk.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Fiskar (Pisces) är en grupp vattenlevande rygg...,"[0.05697632, 0.020736694, -0.028640747, -0.049...",1.145316
4,kanin.txt,/Users/aigineer/Documents/github/RAG_mlops25/r...,Harar och kaniner\n\nArtikel\nDiskussion\nLäs\...,"[-0.021530151, -0.024368286, 0.004486084, -0.0...",1.200752